/**
 * lib/policy-fund/last/knowledge-base.ts
 *
 * /test 페이지 전용 독립 Knowledge Base
 * 4대 기관(중진공, 신보, 기보, 소진공) 정책자금 데이터 포함
 */

// types.ts에서 타입 import
import type {
  InstitutionId,
  InstitutionInfo,
  PolicyFundKnowledge,
  FundTrack,
  IndustryCategory,
  CompanyScale,
  OwnerCharacteristic,
  BusinessAgeException,
  FundingPurpose,
  EligibilityCriteria,
  SupportTerms,
} from './types';

// 타입 re-export
export type {
  InstitutionId,
  InstitutionInfo,
  PolicyFundKnowledge,
  FundTrack,
  IndustryCategory,
  CompanyScale,
  OwnerCharacteristic,
  BusinessAgeException,
  FundingPurpose,
  EligibilityCriteria,
  SupportTerms,
};

// ============================================================================
// 기관 정보
// ============================================================================

export const INSTITUTIONS: Record<InstitutionId, InstitutionInfo> = {
  kosmes: {
    id: 'kosmes',
    name: '중진공',
    fullName: '중소벤처기업진흥공단',
    description: '중소기업 정책자금 융자 전문 기관',
    website: 'https://www.kosmes.or.kr',
    contactNumber: '1357',
  },
  kodit: {
    id: 'kodit',
    name: '신보',
    fullName: '신용보증기금',
    description: '담보력 부족 기업에 신용보증 제공',
    website: 'https://www.kodit.co.kr',
    contactNumber: '1588-6565',
  },
  kibo: {
    id: 'kibo',
    name: '기보',
    fullName: '기술보증기금',
    description: '기술력 기반 신용보증 제공',
    website: 'https://www.kibo.or.kr',
    contactNumber: '1544-1120',
  },
  semas: {
    id: 'semas',
    name: '소진공',
    fullName: '소상공인시장진흥공단',
    description: '소상공인 정책자금 융자 전문 기관',
    website: 'https://www.semas.or.kr',
    contactNumber: '1357',
  },
  seoul_credit: {
    id: 'seoul_credit',
    name: '서울신보',
    fullName: '서울신용보증재단',
    description: '서울 소재 소기업·소상공인 신용보증',
    website: 'https://www.seoulshinbo.co.kr',
    contactNumber: '1577-6119',
  },
  gyeonggi_credit: {
    id: 'gyeonggi_credit',
    name: '경기신보',
    fullName: '경기신용보증재단',
    description: '경기도 소재 소기업·소상공인 신용보증',
    website: 'https://www.gcgf.or.kr',
    contactNumber: '1588-7365',
  },
  mss: {
    id: 'mss',
    name: '중기부',
    fullName: '중소벤처기업부',
    description: '중소기업 정책 총괄 부처',
    website: 'https://www.mss.go.kr',
    contactNumber: '1357',
  },
  motie: {
    id: 'motie',
    name: '산업부',
    fullName: '산업통상자원부',
    description: '산업기술 R&D 지원 부처',
    website: 'https://www.motie.go.kr',
    contactNumber: '1577-0900',
  },
  keiti: {
    id: 'keiti',
    name: '환경산업기술원',
    fullName: '한국환경산업기술원',
    description: '환경부 산하 환경산업 지원기관',
    website: 'https://www.keiti.re.kr',
    contactNumber: '02-2284-1114',
  },
};

// ============================================================================
// 중진공(KOSMES) 정책자금
// ============================================================================

const kosmesFunds: PolicyFundKnowledge[] = [
  {
    id: 'kosmes-startup-general',
    institutionId: 'kosmes',
    track: 'general',
    name: '혁신창업사업화자금 (일반창업)',
    shortName: '일반창업',
    type: 'loan',
    description: '창업 초기 기업의 사업화를 위한 자금 - 기술력 없이도 신청 가능',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { max: 7, description: '창업 7년 이내 중소기업' },
      revenue: { min: 50000000, max: 12000000000, description: '연매출 5천만원 이상 120억원 이하' },
      allowedIndustries: ['manufacturing', 'it_service', 'other_service'],
      excludedIndustries: ['부동산업', '유흥업', '금융업'],
      additionalRequirements: ['사업 안정성 입증 (매출 실적)', '신용관리정보 미등록'],
      exclusionConditions: ['휴·폐업 중인 기업', '세금 체납 중인 기업', '금융기관 연체 중인 기업'],
    },
    terms: {
      amount: { max: 6000000000, unit: '억원', description: '기업당 연간 60억원 이내' },
      interestRate: { min: 2.0, max: 3.5, type: 'variable', description: '정책자금 기준금리 + 가산금리 (연 2.0~3.5%)' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 이내 (거치 2년 포함)' },
      repaymentMethod: '거치 후 원금균등분할상환',
    },
    practicalInfo: {
      processingTime: '접수 후 약 2~4주',
      requiredDocuments: ['사업계획서', '재무제표 (최근 3개년)', '사업자등록증', '법인등기부등본'],
      applicationMethod: '중진공 온라인 신청 (www.kosmes.or.kr)',
      contactInfo: '중진공 콜센터 1357',
    },
    riskFactors: ['최근 매출 감소 시 심사 불리', '창업 후 실적 부족 시 한도 축소 가능', '재무제표 정리 필수'],
    preferentialConditions: ['청년창업기업 금리 0.3%p 우대', '여성기업 금리 우대'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', validFrom: '2025-01-01', confidence: 0.9, notes: '기술력 없이도 신청 가능한 일반창업 트랙' },
  },
  {
    id: 'kosmes-startup-tech',
    institutionId: 'kosmes',
    track: 'general',
    name: '혁신창업사업화자금 (기술기반)',
    shortName: '기술창업',
    type: 'loan',
    description: '기술력 보유 창업기업 전용 - 벤처/이노비즈/특허 필수',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { max: 7, description: '창업 7년 이내 중소기업' },
      requiredConditions: { hasTechnologyCertification: true },
      revenue: { max: 12000000000, description: '연매출 120억원 이하' },
      allowedIndustries: ['manufacturing', 'it_service', 'other_service'],
      excludedIndustries: ['부동산업', '유흥업', '금융업'],
      requiredCertifications: ['venture', 'innobiz', 'patent', 'research_institute'],
      additionalRequirements: ['기술성 평가 통과 필수', '벤처/이노비즈/특허/연구소 중 1개 이상 보유', '신용관리정보 미등록'],
      exclusionConditions: ['휴·폐업 중인 기업', '세금 체납 중인 기업', '금융기관 연체 중인 기업'],
    },
    terms: {
      amount: { max: 6000000000, unit: '억원', description: '기업당 연간 60억원 이내' },
      interestRate: { min: 2.0, max: 3.5, type: 'variable', description: '정책자금 기준금리 + 가산금리 (연 2.0~3.5%)' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 이내 (거치 2년 포함)' },
      repaymentMethod: '거치 후 원금균등분할상환',
    },
    practicalInfo: {
      processingTime: '접수 후 약 2~4주',
      requiredDocuments: ['사업계획서', '재무제표 (최근 3개년)', '사업자등록증', '법인등기부등본', '기술력 증빙 (벤처확인서, 특허증 등)'],
      applicationMethod: '중진공 온라인 신청 (www.kosmes.or.kr)',
      contactInfo: '중진공 콜센터 1357',
    },
    riskFactors: ['기술성 평가 탈락 시 지원 불가', '최근 매출 감소 시 심사 불리', '재무제표 정리 필수'],
    preferentialConditions: ['청년창업기업 금리 0.3%p 우대', '여성기업 금리 우대', '벤처·이노비즈 인증기업 우대'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', validFrom: '2025-01-01', confidence: 0.9, notes: '기술력 보유 필수 - 벤처/이노비즈/특허/연구소' },
  },
  {
    id: 'kosmes-new-market',
    institutionId: 'kosmes',
    track: 'general',
    name: '신시장진출지원자금',
    shortName: '신시장진출',
    type: 'loan',
    description: '수출, 내수 확대, 신사업 진출 기업 지원',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      employeeCount: { min: 5, description: '상시근로자 5인 이상 중소기업' },
      businessAge: { min: 1, description: '업력 1년 이상' },
      revenue: { max: 12000000000, description: '연매출 120억원 이하' },
      allowedIndustries: ['all'],
      requiresExport: true,
      requiredConditions: { hasExportRevenue: true },
      additionalRequirements: ['수출실적 보유 또는 수출계획 수립 기업', '신규 사업 진출 계획 보유'],
      exclusionConditions: ['휴·폐업 중인 기업', '세금 체납', '금융기관 연체'],
    },
    terms: {
      amount: { max: 6000000000, unit: '억원', description: '기업당 연간 60억원 이내' },
      interestRate: { min: 2.0, max: 3.5, type: 'variable', description: '연 2.0~3.5%' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: { processingTime: '약 2~4주', applicationMethod: '중진공 온라인 신청' },
    riskFactors: ['수출 실적 증빙 필요', '신사업 계획의 구체성 필요'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'kosmes-new-growth',
    institutionId: 'kosmes',
    track: 'general',
    name: '신성장기반자금',
    shortName: '신성장',
    type: 'loan',
    description: '성장기 중소기업의 기술혁신, 사업확장 지원 (업력 7년 초과)',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { min: 7, description: '업력 7년 초과 성장기 중소기업' },
      employeeCount: { min: 5, description: '상시근로자 5인 이상' },
      allowedIndustries: ['manufacturing', 'it_service', 'other_service'],
      excludedIndustries: ['부동산업', '유흥업', '금융업'],
      additionalRequirements: ['성장 가능성 높은 중소기업', '벤처/이노비즈/메인비즈 인증 우대', '신용관리정보 미등록'],
      exclusionConditions: ['휴·폐업 중인 기업', '세금 체납 중인 기업', '금융기관 연체 중인 기업'],
    },
    terms: {
      amount: { max: 6000000000, unit: '억원', description: '기업당 연간 60억원 이내' },
      interestRate: { min: 2.0, max: 3.5, type: 'variable', description: '정책자금 기준금리 + 가산금리 (연 2.0~3.5%)' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 이내 (거치 2년 포함)' },
      repaymentMethod: '거치 후 원금균등분할상환',
    },
    practicalInfo: {
      processingTime: '접수 후 약 2~4주',
      requiredDocuments: ['사업계획서', '재무제표 (최근 3개년)', '사업자등록증', '법인등기부등본'],
      applicationMethod: '중진공 온라인 신청 (www.kosmes.or.kr)',
      contactInfo: '중진공 콜센터 1357',
    },
    riskFactors: ['재무상태 심사 중요', '성장 가능성 심사 필요'],
    preferentialConditions: ['벤처/이노비즈/메인비즈 인증기업 금리 우대', '비수도권 기업 금리 0.2%p 우대'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', validFrom: '2026-01-01', confidence: 0.9, notes: '2026년 1.3조원 규모, 업력 7년 초과 성장기 기업 대상' },
  },
  {
    id: 'kosmes-emergency',
    institutionId: 'kosmes',
    track: 'general',
    name: '긴급경영안정자금',
    shortName: '긴급경영',
    type: 'loan',
    description: '경영 위기 상황의 중소기업 긴급 지원',
    fundingPurpose: { working: true, facility: false },
    eligibility: {
      employeeCount: { min: 5, description: '상시근로자 5인 이상 중소기업' },
      requiredConditions: { isEmergencySituation: true },
      additionalRequirements: ['재해·재난 피해 기업', '매출 급감 기업 (전년 대비 20% 이상)', '구조조정 기업'],
      exclusionConditions: ['휴·폐업', '세금 체납', '금융기관 연체 90일 초과'],
    },
    terms: {
      amount: { max: 1000000000, unit: '억원', description: '기업당 10억원 이내' },
      interestRate: { min: 1.5, max: 2.5, type: 'fixed', description: '연 1.5~2.5% (긴급 지원 우대금리)' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: { processingTime: '긴급 처리 (1~2주)' },
    riskFactors: ['피해 증빙 서류 필수', '매출 감소 객관적 증빙 필요'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', confidence: 0.8, notes: '재해/재난 시 수시 접수. 긴급상황 증빙 필수.' },
  },
  {
    id: 'kosmes-investment-loan',
    institutionId: 'kosmes',
    track: 'policy_linked',
    name: '투융자복합금융',
    shortName: '투융자복합',
    type: 'loan',
    description: '투자유치 기업에 투자금액 연계 융자 지원',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      employeeCount: { min: 5, description: '상시근로자 5인 이상 중소기업' },
      businessAge: { min: 2, description: '업력 2년 이상' },
      revenue: { min: 500000000, description: '연매출 5억원 이상' },
      additionalRequirements: ['투자금액 대비 일정 비율 융자'],
      exclusionConditions: ['휴·폐업', '세금 체납', '금융기관 연체'],
    },
    terms: {
      amount: { min: 1000000000, max: 10000000000, unit: '억원', description: '기업당 10~100억원 (투자금액 연동)' },
      interestRate: { min: 1.5, max: 2.5, type: 'variable', description: '연 1.5~2.5% (우대금리)' },
      loanPeriod: { years: 8, gracePeriod: 3, description: '8년 (거치 3년)' },
    },
    practicalInfo: {
      processingTime: '약 4~6주 (투자 검증 포함)',
      requiredDocuments: ['투자계약서', '주주명부', '재무제표', '사업계획서'],
    },
    riskFactors: ['투자 검증 필수', '대규모 자금으로 심사 기간 길음'],
    preferentialConditions: ['시리즈B 이상 투자유치 기업 우대', '기술특례 상장 추진 기업 우대'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '스케일업 기업 대상 대형 자금' },
  },
  {
    id: 'kosmes-restart',
    institutionId: 'kosmes',
    track: 'exclusive',
    name: '재창업자금',
    shortName: '재창업',
    type: 'loan',
    description: '실패 경험 재창업자 사업화 지원',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      employeeCount: { min: 5, description: '상시근로자 5인 이상 중소기업' },
      businessAge: { max: 7, description: '재창업 7년 이내' },
      requiredConditions: { isRestart: true },
      additionalRequirements: ['과거 폐업 경험 보유', '재창업 사업자', '성실실패 인정 또는 회생절차 완료'],
      exclusionConditions: ['악의적 폐업 이력', '금융사기 전력'],
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '기업당 50억원 이내' },
      interestRate: { min: 2.0, max: 3.0, type: 'variable', description: '연 2.0~3.0%' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: {
      processingTime: '약 2~3주',
      requiredDocuments: ['폐업사실증명원', '재창업 사업계획서', '신용회복 증빙'],
    },
    riskFactors: ['과거 폐업 사유 심사', '신용등급 제약 있을 수 있음'],
    preferentialConditions: ['재도전성공패키지 참여기업 우대', '청년 재창업자 금리 우대'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', confidence: 0.8, notes: '재기 지원 정책' },
  },
  {
    id: 'kosmes-social-enterprise',
    institutionId: 'kosmes',
    track: 'exclusive',
    name: '사회적기업전용자금',
    shortName: '사회적기업',
    type: 'loan',
    description: '사회적 가치 실현 기업 전용 - 고용 취약계층 고용·유지 지원',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      requiredConditions: { isSocialEconomyEnterprise: true },
      additionalRequirements: ['사회적기업(인증/예비) 또는 사회적협동조합', '또는 자활기업, 마을기업, 장애인표준사업장', '정상 영업 중, 세금 체납 없음', '고용 취약계층 고용·유지 실적'],
      exclusionConditions: ['휴·폐업 중인 기업', '세금 체납 중인 기업', '금융기관 연체 중인 기업'],
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '기업별 수억 원 이내' },
      interestRate: { min: 1.5, max: 2.5, type: 'variable', description: '정책금리 우대 (연 1.5~2.5%)' },
      loanPeriod: { years: 8, gracePeriod: 3, description: '8년 (거치 3년)' },
      repaymentMethod: '거치 후 원금균등분할상환',
    },
    practicalInfo: {
      processingTime: '약 2~3주',
      requiredDocuments: ['사회적기업 인증서 또는 관련 지정서', '사업자등록증', '재무제표', '고용 현황 자료'],
      applicationMethod: '중진공 지역본부 접수',
      contactInfo: '중진공 콜센터 1357',
    },
    riskFactors: ['사회적 목적 지속 가능성 평가', '고용 유지 실적 확인'],
    preferentialConditions: ['취약계층 고용 비율 높은 기업 우대', '사회적 가치 성과 우수기업 우대'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '사회적경제기업 전용 트랙' },
  },
  {
    id: 'kosmes-smart-factory',
    institutionId: 'kosmes',
    track: 'policy_linked',
    name: '스마트공장지원자금',
    shortName: '스마트공장',
    type: 'loan',
    description: '스마트공장 구축·고도화 시설자금 지원',
    fundingPurpose: { working: false, facility: true },
    eligibility: {
      employeeCount: { min: 5, description: '상시근로자 5인 이상 중소기업' },
      requiredConditions: { hasSmartFactoryPlan: true },
      allowedIndustries: ['manufacturing'],
      additionalRequirements: ['스마트공장 구축 또는 고도화 계획', '제조업 영위', '스마트공장 보급사업 참여 우대'],
      exclusionConditions: ['휴·폐업', '세금 체납'],
    },
    terms: {
      amount: { max: 6000000000, unit: '억원', description: '기업당 60억원 이내' },
      interestRate: { min: 1.5, max: 2.5, type: 'variable', description: '연 1.5~2.5% (시설자금 우대)' },
      loanPeriod: { years: 10, gracePeriod: 4, description: '10년 (거치 4년)' },
    },
    practicalInfo: {
      processingTime: '약 3~4주',
      requiredDocuments: ['스마트공장 구축 계획서', '견적서/투자계획', '재무제표'],
    },
    riskFactors: ['시설투자 계획 구체성 필요', '스마트공장 수준 진단 필요'],
    preferentialConditions: ['스마트공장 보급사업 선정기업 금리 우대', '뿌리산업 기업 우대'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '제조업 디지털화 지원' },
  },
  {
    id: 'kosmes-green-growth',
    institutionId: 'kosmes',
    track: 'policy_linked',
    name: '탄소중립시설자금',
    shortName: '탄소중립',
    type: 'loan',
    description: 'ESG·탄소중립 관련 시설투자 지원',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      employeeCount: { min: 5, description: '상시근로자 5인 이상 중소기업' },
      requiredConditions: { hasEsgInvestmentPlan: true },
      additionalRequirements: ['탄소저감 시설 투자 계획', 'ESG 경영 도입 기업', '환경 관련 인증 보유 우대'],
      exclusionConditions: ['환경법 위반 기업', '휴·폐업'],
    },
    terms: {
      amount: { max: 6000000000, unit: '억원', description: '기업당 60억원 이내' },
      interestRate: { min: 1.0, max: 2.0, type: 'variable', description: '연 1.0~2.0% (정책 우대금리)' },
      loanPeriod: { years: 10, gracePeriod: 4, description: '10년 (거치 4년)' },
    },
    practicalInfo: {
      processingTime: '약 3~4주',
      requiredDocuments: ['탄소저감 투자계획서', '환경 인증서 (있는 경우)', '재무제표'],
    },
    riskFactors: ['환경 관련 시설투자 입증 필요', '탄소저감 효과 계량화 필요'],
    preferentialConditions: ['K-ESG 우수기업 금리 우대', '녹색인증 기업 우대'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', confidence: 0.8, notes: '2050 탄소중립 정책 연계. ESG 투자 계획 필수.' },
  },
  {
    id: 'kosmes-youth-startup',
    institutionId: 'kosmes',
    track: 'exclusive',
    name: '청년전용창업자금',
    shortName: '청년창업',
    type: 'loan',
    description: '만 39세 이하 청년 대표자의 창업 초기 기업 전용 저금리 융자',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: {
        max: 3,
        maxWithException: 7,
        exceptions: ['youth_startup_academy', 'global_startup_academy', 'kibo_youth_guarantee'],
        description: '창업 3년 미만 (예외: 청창사/글로벌창업사관학교 졸업 시 7년)',
      },
      revenue: { max: 12000000000, description: '연매출 120억원 이하 중소기업' },
      allowedIndustries: ['manufacturing', 'it_service', 'other_service'],
      excludedIndustries: ['부동산임대업', '유흥업', '도박업', '금융업'],
      preferredOwnerTypes: ['youth'],
      requiredConditions: { isYouthCompany: true },
      additionalRequirements: ['대표자 만 39세 이하', '창업 3년 미만 또는 예비창업자', '(예외) 청년창업사관학교/글로벌창업사관학교 졸업 시 7년까지', '대한민국 내 사업장 소재'],
      exclusionConditions: ['휴·폐업 중인 기업', '세금 체납 중인 기업', '최근 5년 내 정책자금 3회 이상 수혜', '동일 대표자 부정수급 이력'],
    },
    terms: {
      amount: { max: 100000000, unit: '억원', description: '기업당 1억원 이내 (제조업/지역특화산업 2억원)' },
      interestRate: { min: 2.5, max: 2.5, type: 'fixed', description: '연 2.5% (고정금리)' },
      loanPeriod: { years: 6, gracePeriod: 3, description: '운전 6년(거치 3년), 시설 10년(거치 3년)' },
      repaymentMethod: '거치 후 원금균등분할상환',
    },
    practicalInfo: {
      processingTime: '선착순 접수, 약 2~3주',
      requiredDocuments: ['사업계획서', '사업자등록증 또는 창업계획서', '대표자 신분증 (연령 확인)', '재무제표 (있는 경우)'],
      applicationMethod: '중진공 지역본부 선착순 접수 (온라인 신청)',
      contactInfo: '중진공 콜센터 1357',
    },
    riskFactors: ['선착순 마감으로 접수 시기 중요', '예비창업자는 사업계획서 구체성 필수'],
    preferentialConditions: ['여성 청년창업자 우대', '제조업/IT/친환경 산업 우대', '기보/신보 보증서 발급 시 가점'],
    officialUrl: 'https://www.kosmes.or.kr/nsh/SH/SBI/SHSBI004M0.do',
    meta: { lastUpdated: '2026-01', validFrom: '2025-01-01', confidence: 0.95, notes: '청년 대표자 전용 최저금리 정책자금' },
  },
];

// ============================================================================
// 소진공(SEMAS) 정책자금
// ============================================================================

const semasFunds: PolicyFundKnowledge[] = [
  {
    id: 'semas-micro-enterprise',
    institutionId: 'semas',
    track: 'general',
    name: '소공인특화자금',
    targetScale: ['micro'],
    shortName: '소공인',
    type: 'loan',
    description: '상시근로자 10인 미만 제조업체 전용',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      employeeCount: { max: 10, description: '상시근로자 10인 미만' },
      allowedIndustries: ['manufacturing'],
      additionalRequirements: ['제조업 영위', '소공인 해당 업종'],
    },
    terms: {
      amount: { max: 100000000, unit: '만원', description: '기업당 1억원 이내' },
      interestRate: { min: 2.0, max: 3.0, type: 'fixed', description: '연 2.0~3.0%' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: { applicationMethod: '소진공 지역센터 방문' },
    riskFactors: ['제조업 업종 증빙 필요', '근로자 수 기준 엄격'],
    officialUrl: 'https://www.semas.or.kr/web/main/index.kmdc',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'semas-growth',
    institutionId: 'semas',
    track: 'general',
    name: '성장기반자금',
    shortName: '성장기반',
    type: 'loan',
    description: '성장 단계 소상공인 지원 (소상공인 전용)',
    targetScale: ['micro'],
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      employeeCount: { max: 10, description: '상시근로자 10인 미만 (제조업 외)' },
      additionalRequirements: ['소상공인 해당', '성장 가능성 보유'],
    },
    terms: {
      amount: { max: 100000000, unit: '만원', description: '기업당 1억원 이내' },
      interestRate: { min: 2.5, max: 3.5, type: 'variable', description: '연 2.5~3.5%' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: {
      processingTime: '2~3주',
      requiredDocuments: ['사업자등록증', '재무제표', '매출 증빙'],
    },
    riskFactors: ['소상공인 기준 충족 필수', '매출 기준 확인 필요'],
    officialUrl: 'https://www.semas.or.kr/web/main/index.kmdc',
    meta: { lastUpdated: '2026-01', confidence: 0.8 },
  },
  {
    id: 'semas-emergency',
    institutionId: 'semas',
    track: 'general',
    name: '긴급경영안정자금',
    shortName: '소진공 긴급',
    type: 'loan',
    description: '재해·경영위기 소상공인 긴급 지원 (소상공인 전용)',
    targetScale: ['micro'],
    fundingPurpose: { working: true, facility: false },
    eligibility: {
      additionalRequirements: ['재해 피해 소상공인', '경영위기 소상공인'],
      requiredConditions: { isEmergencySituation: true },
    },
    terms: {
      amount: { max: 50000000, unit: '만원', description: '기업당 5천만원 이내' },
      interestRate: { min: 1.5, max: 2.0, type: 'fixed', description: '연 1.5~2.0% (긴급 우대)' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: { processingTime: '긴급 처리 (1주 이내)' },
    riskFactors: ['피해 증빙 필수', '지원 한도 제한적'],
    officialUrl: 'https://www.semas.or.kr/web/main/index.kmdc',
    meta: { lastUpdated: '2026-01', confidence: 0.8, notes: '재해 시 수시 접수' },
  },
  {
    id: 'semas-general',
    institutionId: 'semas',
    track: 'general',
    name: '일반경영안정자금',
    shortName: '소진공 일반',
    type: 'loan',
    description: '일반 소상공인 운전자금 지원 (소상공인 전용)',
    targetScale: ['micro'],
    fundingPurpose: { working: true, facility: false },
    eligibility: {
      employeeCount: { max: 5, description: '상시근로자 5인 미만 (제조업 10인 미만)' },
      allowedIndustries: ['wholesale_retail', 'food_service', 'other_service'],
      additionalRequirements: ['소상공인 해당', '사업자등록 후 6개월 이상'],
      exclusionConditions: ['휴·폐업', '세금 체납', '유흥업종'],
    },
    terms: {
      amount: { max: 70000000, unit: '만원', description: '기업당 7천만원 이내' },
      interestRate: { min: 2.5, max: 3.5, type: 'fixed', description: '연 2.5~3.5%' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['사업자등록증', '매출 증빙', '신분증'],
      applicationMethod: '소진공 지역센터 또는 온라인',
    },
    riskFactors: ['소상공인 기준 충족 필수', '업종별 지원 제외 확인'],
    officialUrl: 'https://www.semas.or.kr/web/board/webBoardList.kmdc?bCd=policy_fund',
    meta: { lastUpdated: '2026-01', confidence: 0.9 },
  },
  {
    id: 'semas-female',
    institutionId: 'semas',
    track: 'exclusive',
    name: '여성기업지원자금',
    shortName: '여성기업',
    type: 'loan',
    description: '여성 대표 소상공인 전용 지원 (소상공인 전용)',
    targetScale: ['micro'],
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      employeeCount: { max: 5, description: '상시근로자 5인 미만 (제조업 10인 미만)' },
      preferredOwnerTypes: ['female'],
      requiredConditions: { isFemale: true },
      additionalRequirements: ['여성 대표자 기업', '소상공인 해당', '여성기업확인서 보유 우대'],
    },
    terms: {
      amount: { max: 70000000, unit: '만원', description: '기업당 7천만원 이내' },
      interestRate: { min: 2.0, max: 3.0, type: 'fixed', description: '연 2.0~3.0% (우대금리)' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['사업자등록증', '여성기업확인서 (있는 경우)', '매출 증빙'],
    },
    riskFactors: ['여성 대표자 요건 확인'],
    preferentialConditions: ['여성기업확인서 보유 시 금리 우대', '보증료 감면'],
    officialUrl: 'https://www.semas.or.kr/web/board/webBoardList.kmdc?bCd=policy_fund',
    meta: { lastUpdated: '2026-01', confidence: 0.9 },
  },
  {
    id: 'semas-disabled',
    institutionId: 'semas',
    track: 'exclusive',
    name: '장애인기업지원자금',
    shortName: '장애인기업',
    type: 'loan',
    description: '장애인 대표 기업 또는 장애인표준사업장 전용 지원',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      preferredOwnerTypes: ['disabled'],
      requiredConditions: { isDisabledCompany: true },
      additionalRequirements: ['장애인 대표자 기업 또는 장애인표준사업장', '장애인복지법에 따른 장애인'],
    },
    terms: {
      amount: { max: 100000000, unit: '만원', description: '기업당 1억원 이내' },
      interestRate: { min: 2.0, max: 2.5, type: 'fixed', description: '연 2.0~2.5% (우대금리)' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['장애인등록증', '사업자등록증', '매출 증빙'],
    },
    riskFactors: ['장애인 대표자 요건 확인'],
    preferentialConditions: ['보증료 감면', '우대금리 적용'],
    officialUrl: 'https://www.semas.or.kr/web/board/webBoardList.kmdc?bCd=policy_fund',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'semas-youth',
    institutionId: 'semas',
    track: 'exclusive',
    name: '청년고용특별자금',
    shortName: '청년소상공인',
    type: 'loan',
    description: '청년 소상공인 또는 청년 고용 소상공인 지원 (소상공인 전용)',
    targetScale: ['micro'],
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      preferredOwnerTypes: ['youth'],
      requiredConditions: { isYouthCompany: true },
      additionalRequirements: ['만 39세 이하 청년 대표자', '또는 청년 정규직 고용 소상공인', '소상공인 해당'],
    },
    terms: {
      amount: { max: 100000000, unit: '만원', description: '기업당 1억원 이내' },
      interestRate: { min: 2.0, max: 3.0, type: 'fixed', description: '연 2.0~3.0% (우대금리)' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['대표자 신분증 (연령 확인)', '사업자등록증', '청년 고용 증빙 (해당 시)'],
    },
    riskFactors: ['청년 기준 연령 확인', '고용 실적 검증 (청년고용 우대 시)'],
    preferentialConditions: ['청년창업 우대금리', '보증료 감면'],
    officialUrl: 'https://www.semas.or.kr/web/board/webBoardList.kmdc?bCd=policy_fund',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'semas-youth-employment',
    institutionId: 'semas',
    track: 'exclusive',
    name: '청년고용연계자금',
    shortName: '청년고용연계',
    type: 'loan',
    description: '청년 소상공인 또는 청년 고용 소상공인 전용 자금 (소상공인 전용)',
    targetScale: ['micro'],
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { max: 3, description: '사업 유지기간 3년 미만 청년 소상공인' },
      employeeCount: { max: 10, description: '상시근로자 10인 미만 (제조업 외 5인 미만)' },
      preferredOwnerTypes: ['youth'],
      requiredConditions: { hasYouthEmploymentPlan: true },
      additionalRequirements: ['만 39세 이하 청년 대표자', '또는 상시근로자 과반수가 청년', '또는 최근 1년 내 청년 근로자 1명 이상 고용'],
      exclusionConditions: ['휴·폐업', '세금 체납', '유흥업종'],
    },
    terms: {
      amount: { max: 100000000, unit: '만원', description: '기업당 1억원 이내' },
      interestRate: { min: 2.0, max: 3.0, type: 'fixed', description: '연 2.0~3.0% (청년 우대금리)' },
      loanPeriod: { years: 5, gracePeriod: 2, description: '5년 (거치 2년)' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['대표자 신분증 (연령 확인)', '사업자등록증', '4대보험 가입자 명부 (청년고용 증빙)'],
      applicationMethod: '소진공 지역센터 또는 온라인',
      contactInfo: '1357',
    },
    riskFactors: ['청년 기준 연령 확인 필수', '청년 고용 실적 검증'],
    preferentialConditions: ['청년 대표자 우대금리', '청년 고용 증가 시 추가 우대'],
    officialUrl: 'https://www.semas.or.kr/web/board/webBoardList.kmdc?bCd=policy_fund',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '청년 고용 창출 연계 정책' },
  },
];

// ============================================================================
// 신보(KODIT) 보증상품
// ============================================================================

const koditFunds: PolicyFundKnowledge[] = [
  {
    id: 'kodit-general',
    institutionId: 'kodit',
    track: 'guarantee',
    name: '일반보증',
    shortName: '신보 일반',
    type: 'guarantee',
    description: '담보력 부족 중소기업에 신용보증서 발급',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      creditRating: { max: 6, description: '신용등급 6등급 이상' },
      allowedIndustries: ['all'],
      excludedIndustries: ['부동산임대업', '유흥주점업'],
      exclusionConditions: ['세금 체납', '금융기관 연체', '신용관리정보 등록', '휴·폐업'],
    },
    terms: {
      amount: { max: 3000000000, unit: '억원', description: '기업당 30억원 이내' },
      guaranteeRatio: { min: 70, max: 100, description: '보증비율 70~100%' },
    },
    practicalInfo: {
      processingTime: '약 1~2주',
      applicationMethod: '신보 영업점 방문 또는 온라인',
      contactInfo: '1588-6565',
    },
    riskFactors: ['신용등급에 따라 보증 한도 차등', '보증료 연 0.5~2.0% 발생'],
    preferentialConditions: ['청년·여성 기업 보증료 감면', '벤처기업 우대'],
    officialUrl: 'https://www.kodit.co.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.9 },
  },
  {
    id: 'kodit-startup',
    institutionId: 'kodit',
    track: 'guarantee',
    name: '창업기업보증',
    shortName: '신보 창업',
    type: 'guarantee',
    description: '창업 초기 기업 전용 신용보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { max: 5, description: '창업 5년 이내' },
      excludedIndustries: ['부동산임대업', '유흥주점업'],
    },
    terms: {
      amount: { max: 500000000, unit: '억원', description: '기업당 5억원 이내' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100% (창업 우대)' },
    },
    practicalInfo: {
      processingTime: '약 1주',
      requiredDocuments: ['사업계획서', '사업자등록증', '대표자 신용정보동의서'],
    },
    riskFactors: ['창업 후 실적 부족 시 한도 제한', '대표자 신용등급 중요'],
    preferentialConditions: ['청년창업자 보증료 0.2%p 감면', '기술창업 우대'],
    officialUrl: 'https://www.kodit.co.kr/kodit/cm/cntnts/cntntsView.do?mi=3145&cntntsId=11379',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'kodit-innovation-growth',
    institutionId: 'kodit',
    track: 'policy_linked',
    name: '혁신성장보증',
    shortName: '신보 혁신성장',
    type: 'guarantee',
    description: '4차산업혁명 관련 혁신기업 전용 보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['4차산업혁명 관련 업종 (AI, 빅데이터, IoT 등)', '혁신성장 분야 영위 기업', '기술혁신형 중소기업'],
      excludedIndustries: ['부동산임대업', '유흥주점업'],
      requiredConditions: { is4thIndustry: true },
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '기업당 50억원 이내' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 1~2주',
      requiredDocuments: ['사업계획서', '기술관련 자료', '재무제표'],
    },
    riskFactors: ['혁신성장 분야 해당 여부 심사', '기술력 입증 필요'],
    preferentialConditions: ['혁신성장 유니콘 기업 우대', '특허 보유 기업 보증료 감면'],
    officialUrl: 'https://www.kodit.co.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'kodit-job-creation',
    institutionId: 'kodit',
    track: 'policy_linked',
    name: '일자리창출보증',
    shortName: '신보 일자리',
    type: 'guarantee',
    description: '고용 확대 기업에 보증 우대 지원',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['최근 1년 내 고용 증가 기업', '또는 고용 확대 계획 보유', '정규직 채용 우대'],
      exclusionConditions: ['고용 감소 기업', '세금 체납'],
    },
    terms: {
      amount: { max: 3000000000, unit: '억원', description: '기업당 30억원 이내' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 1~2주',
      requiredDocuments: ['고용 증가 증빙 (4대보험 가입자 명부)', '채용 계획서', '재무제표'],
    },
    riskFactors: ['고용 증가 실적 입증 필요', '일시적 채용은 인정 제한'],
    preferentialConditions: ['청년 고용 증가 시 보증료 추가 감면', '지역인재 고용 우대'],
    officialUrl: 'https://www.kodit.co.kr/kodit/cm/cntnts/cntntsView.do?mi=2833&cntntsId=11387',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'kodit-female',
    institutionId: 'kodit',
    track: 'exclusive',
    name: '여성기업우대보증',
    shortName: '신보 여성',
    type: 'guarantee',
    description: '여성 대표 중소기업 전용 우대 보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      preferredOwnerTypes: ['female'],
      requiredConditions: { isFemale: true },
      additionalRequirements: ['여성 대표자 기업', '중소기업 또는 소상공인', '여성기업확인서 보유 우대'],
      excludedIndustries: ['부동산임대업', '유흥업'],
    },
    terms: {
      amount: { max: 3000000000, unit: '억원', description: '기업당 30억원 이내' },
      guaranteeRatio: { min: 90, max: 100, description: '보증비율 90~100% (여성기업 우대), 보증료 0.5%p 감면' },
    },
    practicalInfo: {
      processingTime: '약 1~2주',
      requiredDocuments: ['사업자등록증', '재무제표', '여성기업확인서 (있는 경우)', '대표자 신분증'],
    },
    riskFactors: ['여성 대표자 요건 확인'],
    preferentialConditions: ['보증비율 100% 가능', '보증료 0.5%p 감면', '여성기업확인서 보유 시 추가 우대'],
    officialUrl: 'https://www.kodit.co.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'kodit-export',
    institutionId: 'kodit',
    track: 'policy_linked',
    name: '수출기업보증',
    shortName: '신보 수출',
    type: 'guarantee',
    description: '수출 실적 또는 수출 계획 기업 전용 보증',
    fundingPurpose: { working: true, facility: false },
    eligibility: {
      additionalRequirements: ['수출 실적 보유 기업', '또는 수출 계획 수립 기업', '해외 바이어 확보'],
      excludedIndustries: ['부동산임대업'],
      requiredConditions: { hasExportRevenue: true },
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '기업당 50억원 이내' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 1~2주',
      requiredDocuments: ['수출실적 증빙 (수출신고필증 등)', '수출계약서 또는 L/C', '재무제표'],
    },
    riskFactors: ['수출 실적 또는 계획 검증', '바이어 신용도 확인'],
    preferentialConditions: ['수출 신규 진출 기업 우대', '강소기업 우대'],
    officialUrl: 'https://www.kodit.co.kr/kodit/cm/cntnts/cntntsView.do?mi=2834&cntntsId=11388',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'kodit-youth-dream',
    institutionId: 'kodit',
    track: 'exclusive',
    name: '청년희망드림보증',
    shortName: '신보 청년드림',
    type: 'guarantee',
    description: '17~39세 청년 대표자 창업기업 전용 고보증비율 상품',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { max: 7, description: '창업 7년 이내' },
      allowedIndustries: ['manufacturing', 'it_service', 'other_service'],
      excludedIndustries: ['부동산임대업', '유흥주점업'],
      preferredOwnerTypes: ['youth'],
      requiredConditions: { isYouthCompany: true },
      additionalRequirements: ['대표자 만 17~39세', '창업 7년 이내 기업', '제조업, 유망창업 업종 우대'],
      exclusionConditions: ['세금 체납', '금융기관 연체', '신용관리정보 등록'],
    },
    terms: {
      amount: { max: 300000000, unit: '억원', description: '기업당 3억원 이내' },
      guaranteeRatio: { min: 95, max: 95, description: '보증비율 95% (고정)' },
    },
    practicalInfo: {
      processingTime: '약 1주',
      requiredDocuments: ['사업자등록증', '대표자 신분증', '재무제표 또는 부가세신고서'],
      applicationMethod: '신보 영업점 또는 온라인 (온비즈)',
      contactInfo: '1588-6565',
    },
    riskFactors: ['대표자 연령 증빙 필수', '창업 7년 초과 시 일반보증 전환'],
    preferentialConditions: ['보증료 0.3% 고정 (일반 0.5~2.0%)', '보증비율 95% 고정 (일반 70~100%)'],
    officialUrl: 'https://www.kodit.co.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.9, notes: '청년 전용 최고 보증비율 상품' },
  },
  {
    id: 'kodit-youth-startup-special',
    institutionId: 'kodit',
    track: 'exclusive',
    name: '청년창업특례보증',
    shortName: '신보 청년창업특례',
    type: 'guarantee',
    description: '예비창업자 또는 창업 3년 이내 청년 중소기업 특례보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { max: 3, description: '예비창업자 또는 창업 3년 이내' },
      preferredOwnerTypes: ['youth'],
      requiredConditions: { isYouthCompany: true },
      excludedIndustries: ['부동산임대업', '유흥주점업'],
      additionalRequirements: ['대표자 만 39세 이하', '예비창업자 또는 창업 3년 이내 중소기업'],
      exclusionConditions: ['세금 체납', '금융기관 연체', '신용관리정보 등록'],
    },
    terms: {
      amount: { max: 300000000, unit: '억원', description: '동일 차주 3억원 이내 (운전 1억 + 시설 2억)' },
      guaranteeRatio: { min: 90, max: 100, description: '보증비율 90~100%' },
    },
    practicalInfo: {
      processingTime: '약 1주',
      requiredDocuments: ['사업계획서', '대표자 신분증', '사업자등록증 (있는 경우)'],
      applicationMethod: '신보 영업점 또는 온라인',
      contactInfo: '1588-6565',
    },
    riskFactors: ['예비창업자 사업계획서 심사', '창업 3년 초과 시 일반보증 전환'],
    preferentialConditions: ['예비창업자 지원 가능', '보증료 감면', '고보증비율'],
    officialUrl: 'https://www.kodit.co.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '예비창업자 포함 청년 특례' },
  },
  {
    id: 'kodit-startup-nest',
    institutionId: 'kodit',
    track: 'policy_linked',
    name: 'Start-up NEST',
    shortName: '신보 스타트업NEST',
    type: 'guarantee',
    description: '혁신스타트업 성장주기별 보증+투자+컨설팅 One-stop 융복합 육성 플랫폼',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { max: 7, description: '창업 7년 이내 혁신스타트업' },
      additionalRequirements: ['혁신스타트업 (기술기반 창업)', '성장 잠재력 보유', '스케일업 의지'],
      requiredConditions: { isVentureCompany: true },
      excludedIndustries: ['부동산임대업', '유흥주점업'],
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '단계별 최대 50억원' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['사업계획서', '재무제표', '벤처기업확인서', '기술사업계획서'],
      applicationMethod: '신보 영업점 또는 온라인',
      contactInfo: '1588-6565',
    },
    riskFactors: ['성장성 평가 중요', '단계별 지원으로 초기 한도 제한'],
    preferentialConditions: ['보증+투자+컨설팅 융복합 지원', '전담 조직 밀착 지원', '후속 투자 연계'],
    officialUrl: 'https://www.kodit.co.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '혁신스타트업 육성 플랫폼' },
  },
  {
    id: 'kodit-innovation-icon',
    institutionId: 'kodit',
    track: 'policy_linked',
    name: '혁신아이콘보증',
    shortName: '신보 혁신아이콘',
    type: 'guarantee',
    description: '미래 글로벌 유니콘기업 성장 가능성이 높은 혁신스타트업 집중 육성',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { min: 2, max: 12, description: '업력 2~12년 (공식 확인)' },
      revenue: { min: 1000000000, description: '매출 10억 이상 + 매출성장률 10% 이상 (또는 투자유치 30억 이상)' },
      additionalRequirements: ['(조건1) 매출 10억 이상 + 매출성장률 10% 이상 (공식 확인)', '(조건2) 또는 투자유치 30억 이상 (공식 확인)', '유니콘 성장 가능성 높은 혁신스타트업', '글로벌 진출 계획'],
      requiredConditions: { isVentureCompany: true },
      excludedIndustries: ['부동산임대업', '유흥주점업'],
    },
    terms: {
      amount: { max: 20000000000, unit: '억원', description: '최대 200억원 (공식 확인)' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 3주',
      requiredDocuments: ['사업계획서', '재무제표', '투자유치 실적 증빙', '글로벌 진출 계획서'],
      applicationMethod: '신보 영업점',
      contactInfo: '1588-6565',
    },
    riskFactors: ['선정 경쟁 치열', '성장성 입증 필요'],
    preferentialConditions: ['전담 조직 집중 육성', '스케일업 프로그램 연계', '후속 투자 연계'],
    officialUrl: 'https://www.kodit.co.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.95, notes: '공식 확인: 업력 2~12년, 매출10억+성장률10% 또는 투자30억+, 한도 200억' },
  },
  {
    id: 'kodit-restart',
    institutionId: 'kodit',
    track: 'exclusive',
    name: '재도약보증',
    shortName: '신보 재도약',
    type: 'guarantee',
    description: '경영위기 극복 또는 재창업 기업 전용 보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['재창업 기업', '또는 경영위기 극복 기업', '사업전환 추진 기업'],
      requiredConditions: { isRestart: true },
      excludedIndustries: ['부동산임대업', '유흥주점업'],
    },
    terms: {
      amount: { max: 500000000, unit: '억원', description: '최대 5억원' },
      guaranteeRatio: { min: 90, max: 100, description: '보증비율 90~100%' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['재창업 사업계획서', '폐업사실확인서 (재창업 시)', '신용회복 증빙 (해당 시)'],
      applicationMethod: '신보 영업점',
      contactInfo: '1588-6565',
    },
    riskFactors: ['재창업 사유 소명 필요', '신용상태 확인'],
    preferentialConditions: ['재창업자 전용', '보증료 감면', '신용회복자 지원'],
    officialUrl: 'https://www.kodit.co.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '재창업/경영위기 극복 기업 전용' },
  },
  {
    id: 'kodit-social-venture',
    institutionId: 'kodit',
    track: 'exclusive',
    name: '소셜벤처보증',
    shortName: '신보 소셜벤처',
    type: 'guarantee',
    description: '사회적가치 창출 기술혁신 기업 및 사회적기업 전용 보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['사회적 가치 창출 목적 기업', '사회적기업 또는 예비사회적기업', '소셜벤처 인증 기업'],
      requiredConditions: { isSocialEconomyEnterprise: true },
      excludedIndustries: ['부동산임대업', '유흥주점업'],
    },
    terms: {
      amount: { max: 1000000000, unit: '억원', description: '최대 10억원' },
      guaranteeRatio: { min: 90, max: 100, description: '보증비율 90~100%' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['사업계획서', '사회적기업 인증서', '사회적가치 측정 보고서'],
      applicationMethod: '신보 영업점',
      contactInfo: '1588-6565',
    },
    riskFactors: ['사회적가치 창출 입증 필요', '인증/확인 서류 필수'],
    preferentialConditions: ['사회적기업 전용', '보증료 감면', '높은 보증비율'],
    officialUrl: 'https://www.kodit.co.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '사회적가치 창출 기업 전용' },
  },
  {
    id: 'kodit-green-new-deal',
    institutionId: 'kodit',
    track: 'policy_linked',
    name: '녹색전환보증',
    shortName: '신보 녹색전환',
    type: 'guarantee',
    description: '탄소중립 전환을 위한 녹색 설비 투자 기업 지원',
    fundingPurpose: { working: false, facility: true },
    eligibility: {
      additionalRequirements: ['탄소중립 전환 투자 계획', '녹색 공정·설비·기술 투자', 'ESG 경영 추진 기업'],
      requiredConditions: { hasEsgInvestmentPlan: true },
      excludedIndustries: ['부동산임대업', '유흥주점업'],
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '최대 50억원' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['녹색투자 계획서', '설비 투자 견적서', 'ESG 경영 계획서'],
      applicationMethod: '신보 영업점',
      contactInfo: '1588-6565',
    },
    riskFactors: ['녹색투자 계획 구체성 필요', '설비투자 실행력 검증'],
    preferentialConditions: ['탄소중립 전환 기업 우대', '보증료 감면', 'ESG 컨설팅 연계'],
    officialUrl: 'https://www.kodit.co.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '탄소중립 전환 기업 지원' },
  },
];

// ============================================================================
// 기보(KIBO) 보증상품
// ============================================================================

const kiboFunds: PolicyFundKnowledge[] = [
  {
    id: 'kibo-startup',
    institutionId: 'kibo',
    track: 'guarantee',
    name: '창업기업보증',
    shortName: '기보 창업',
    type: 'guarantee',
    description: '창업 7년 이내 중소기업 전용 신용보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { max: 7, description: '창업 7년 이내' },
      revenue: { max: 100000000000, description: '매출 1000억원 이하 중소기업' },
      excludedIndustries: ['부동산업', '금융업', '유흥업'],
    },
    terms: {
      amount: { max: 3000000000, unit: '억원', description: '기업당 30억원 이내' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '1~2주',
      requiredDocuments: ['사업자등록증', '재무제표', '사업계획서', '법인등기부등본'],
    },
    riskFactors: ['신용등급에 따라 보증비율 차등', '업력 7년 초과 시 일반보증으로 전환'],
    preferentialConditions: ['창업 3년 이내 보증료 감면', '기술창업기업 우대'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.9 },
  },
  {
    id: 'kibo-tech-evaluation',
    institutionId: 'kibo',
    track: 'guarantee',
    name: '기술평가보증',
    shortName: '기보 기술평가',
    type: 'guarantee',
    description: '기술력 보유 기업에 기술평가 기반 보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['기술력 보유 (특허, 기술인력 등)', '기술사업성 평가 통과'],
      excludedIndustries: ['부동산업', '금융업'],
      requiredConditions: { hasTechnologyCertification: true },
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '기업당 50억원 이내' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '기술평가 포함 2~3주',
      requiredDocuments: ['기술관련 서류 (특허, 인증서 등)', '사업계획서', '재무제표'],
    },
    riskFactors: ['기술평가 등급에 따라 한도 차등', '기술성 입증 서류 준비 필요'],
    preferentialConditions: ['우수기술 TCB등급 기업 우대', 'IP(지식재산) 보유기업 우대'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.9 },
  },
  {
    id: 'kibo-venture-startup',
    institutionId: 'kibo',
    track: 'guarantee',
    name: '혁신스타트업보증',
    shortName: '기보 스타트업',
    type: 'guarantee',
    description: '벤처·이노비즈 인증 기업 전용 보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['벤처기업 확인', '또는 이노비즈 인증', '기술혁신형 중소기업'],
      requiredConditions: { isVentureCompany: true },
      excludedIndustries: ['부동산업', '금융업'],
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '기업당 50억원 이내' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 1~2주',
      requiredDocuments: ['벤처기업확인서 또는 이노비즈 인증서', '사업계획서', '재무제표'],
    },
    riskFactors: ['인증 유효기간 확인 필요', '기술력 유지 필요'],
    preferentialConditions: ['벤처/이노비즈 인증기업 보증료 감면', '우대 한도 적용'],
    officialUrl: 'https://www.kibo.or.kr/vc/index.do',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'kibo-ip-collateral',
    institutionId: 'kibo',
    track: 'policy_linked',
    name: 'IP담보보증',
    shortName: '기보 IP담보',
    type: 'guarantee',
    description: '특허, 실용신안 등 지식재산권 담보 보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['특허권, 실용신안권 보유', 'IP 가치평가 가능', '기술사업화 계획'],
      requiredConditions: { hasPatent: true },
    },
    terms: {
      amount: { max: 3000000000, unit: '억원', description: '기업당 30억원 이내 (IP 가치 연동)' },
      guaranteeRatio: { min: 80, max: 100, description: '보증비율 80~100%' },
    },
    practicalInfo: {
      processingTime: '약 3~4주 (IP 가치평가 포함)',
      requiredDocuments: ['특허/실용신안 등록증', 'IP 활용 계획서', '재무제표'],
    },
    riskFactors: ['IP 가치평가에 따른 한도 변동', 'IP 사업화 실적 중요'],
    preferentialConditions: ['우수 IP 보유 기업 보증료 감면', 'IP 매출 비중 높은 기업 우대'],
    officialUrl: 'https://www.kibo.or.kr/main/contents.do?menuNo=200047',
    meta: { lastUpdated: '2026-01', confidence: 0.8 },
  },
  {
    id: 'kibo-rnd',
    institutionId: 'kibo',
    track: 'policy_linked',
    name: 'R&D보증',
    shortName: '기보 R&D',
    type: 'guarantee',
    description: '연구개발 투자 기업 전용 보증',
    fundingPurpose: { working: true, facility: false },
    eligibility: {
      additionalRequirements: ['연구개발 투자 실적 또는 계획', '기업부설연구소 또는 연구개발전담부서 보유', 'R&D 과제 수행 기업 우대'],
      requiredConditions: { hasRndActivity: true },
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '기업당 50억원 이내' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 2~3주',
      requiredDocuments: ['연구소 인정서', 'R&D 투자 계획/실적', '재무제표'],
    },
    riskFactors: ['R&D 투자 계획 구체성 필요', '연구개발 역량 심사'],
    preferentialConditions: ['정부 R&D 과제 수행 기업 우대', '연구인력 비율 높은 기업 우대'],
    officialUrl: 'https://www.kibo.or.kr/main/contents.do?menuNo=200046',
    meta: { lastUpdated: '2026-01', confidence: 0.85 },
  },
  {
    id: 'kibo-cultural-contents',
    institutionId: 'kibo',
    track: 'policy_linked',
    name: '문화콘텐츠보증',
    shortName: '기보 문화콘텐츠',
    type: 'guarantee',
    description: '게임, 영상, 음악, 공연 등 문화콘텐츠 기업 전용',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      allowedIndustries: ['it_service'],
      additionalRequirements: ['문화콘텐츠 제작/유통 기업', '게임, 영상, 음악, 공연, 출판 등', '콘텐츠 제작 실적 또는 계획'],
      requiredConditions: { isCulturalContents: true },
    },
    terms: {
      amount: { max: 3000000000, unit: '억원', description: '기업당 30억원 이내' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 2~3주',
      requiredDocuments: ['콘텐츠 제작/유통 계획서', '기존 콘텐츠 실적', '재무제표'],
    },
    riskFactors: ['콘텐츠 수익성 평가', '지식재산권 확보 여부'],
    preferentialConditions: ['한류 콘텐츠 기업 우대', 'IP 보유 기업 우대'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.8 },
  },
  {
    id: 'kibo-pre-startup',
    institutionId: 'kibo',
    track: 'guarantee',
    name: '예비창업자보증',
    shortName: '기보 예비창업',
    type: 'guarantee',
    description: '사업자등록 전 예비창업자 전용 보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { max: 0, description: '예비창업자 (사업자등록 전)' },
      additionalRequirements: ['사업자등록 전 예비창업자', '창업계획 보유', '기술력 또는 사업성 검증'],
    },
    terms: {
      amount: { max: 200000000, unit: '억원', description: '기업당 2억원 이내' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 2~3주',
      requiredDocuments: ['창업계획서', '기술/아이디어 증빙', '대표자 신분증'],
    },
    riskFactors: ['창업계획 구체성 중요', '대표자 역량 평가'],
    preferentialConditions: ['예비창업자 지원 가능', '창업지원사업 연계 우대'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.8, notes: '법인 설립 전 지원 가능' },
  },
  {
    id: 'kibo-youth-techstar',
    institutionId: 'kibo',
    track: 'exclusive',
    name: '청년테크스타보증',
    shortName: '기보 청년테크',
    type: 'guarantee',
    description: '우수 기술력 보유 청년 창업기업 전용 프리미엄 보증 (공식: 5년 이내, 만17~39세)',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      businessAge: { max: 5, description: '창업 5년 이내 (공식 확인)' },
      preferredOwnerTypes: ['youth'],
      requiredConditions: { isYouthCompany: true, hasTechnologyCertification: true },
      additionalRequirements: ['대표자 만 17~39세 (공식 확인)', '기술력 보유 (특허, 벤처 등)', '창업 5년 이내'],
      excludedIndustries: ['부동산업', '금융업', '유흥업'],
    },
    terms: {
      amount: { max: 300000000, unit: '억원', description: '기업당 3억원 이내' },
      guaranteeRatio: { min: 95, max: 100, description: '보증비율 95~100% (청년 우대)' },
    },
    practicalInfo: {
      processingTime: '약 1~2주',
      requiredDocuments: ['대표자 신분증', '사업자등록증', '기술 관련 증빙 (특허, 벤처확인서 등)', '재무제표'],
      applicationMethod: '기보 영업점',
      contactInfo: '1544-1120',
    },
    riskFactors: ['청년 연령 기준 엄격', '기술력 입증 필수'],
    preferentialConditions: ['보증비율 95~100%', '보증료 감면', '청년 전용 프리미엄 지원'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.9, notes: '2025년 신설 청년 기술창업 전용' },
  },
  {
    id: 'kibo-unicorn',
    institutionId: 'kibo',
    track: 'policy_linked',
    name: '유니콘기업보증',
    shortName: '기보 유니콘',
    type: 'guarantee',
    description: '기업가치 1,000억원 이상 또는 지역스타기업 중 유니콘 성장 잠재력 보유 기업',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['기업가치 1,000억원 이상 (공식 확인)', '또는 지역스타기업 (시장검증/성장성/혁신성 충족)', '기술사업평가등급 B등급 이상 (공식 확인)'],
      requiredConditions: { isVentureCompany: true },
      excludedIndustries: ['부동산업', '금융업', '유흥업'],
    },
    terms: {
      amount: { max: 20000000000, unit: '억원', description: '기업당 최대 200억원 (공식 확인: 선정연도 100억, 차년도 잔여)' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85% (공식 확인, 특별출연협약 시 100%)' },
    },
    practicalInfo: {
      processingTime: '약 3주',
      requiredDocuments: ['사업계획서', '재무제표', '기업가치 평가서', '투자유치 실적 증빙'],
      applicationMethod: '기보 영업점',
      contactInfo: '1544-1120',
    },
    riskFactors: ['선정 경쟁 치열', '기업가치 평가 필요'],
    preferentialConditions: ['최대 200억 지원', '유니콘 육성 프로그램 연계', '전담 지원'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.95, notes: '공식 확인: 기업가치 1000억+, B등급+, 한도 200억, 비율 85%' },
  },
  {
    id: 'kibo-green-energy',
    institutionId: 'kibo',
    track: 'policy_linked',
    name: '신재생에너지보증',
    shortName: '기보 신재생에너지',
    type: 'guarantee',
    description: '신재생에너지 분야 특화 기술평가 기반 보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['신재생에너지 발전기업', '또는 신재생에너지 산업기업', '태양광, 풍력, 수소 등'],
      excludedIndustries: ['부동산업', '금융업'],
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '최대 50억원' },
      interestRate: { min: 0.5, max: 0.7, type: 'fixed', description: '발전기업 0.5% 고정, 산업기업 0.2%p 차감' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['사업계획서', '재무제표', '신재생에너지 사업 인허가 서류', '발전사업 허가증 (해당 시)'],
      applicationMethod: '기보 영업점',
      contactInfo: '1544-1120',
    },
    riskFactors: ['신재생에너지 분야 전문 평가', '사업 인허가 필수'],
    preferentialConditions: ['발전기업 고정 보증료율 0.5%', '산업기업 보증료 0.2%p 차감', '전용 평가모형 적용'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '신재생에너지 분야 특화 보증' },
  },
  {
    id: 'kibo-green-transition',
    institutionId: 'kibo',
    track: 'policy_linked',
    name: '녹색전환보증',
    shortName: '기보 녹색전환',
    type: 'guarantee',
    description: '녹색전환 공정·설비·기술 투자 기업 지원',
    fundingPurpose: { working: false, facility: true },
    eligibility: {
      additionalRequirements: ['녹색 공정·설비·기술 투자 계획', '탄소중립 전환 추진 기업', 'ESG 경영 도입 기업'],
      requiredConditions: { hasEsgInvestmentPlan: true },
      excludedIndustries: ['부동산업', '금융업'],
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '최대 50억원' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['녹색투자 계획서', '설비 투자 견적서', 'ESG 경영 계획서'],
      applicationMethod: '기보 영업점',
      contactInfo: '1544-1120',
    },
    riskFactors: ['녹색투자 계획 구체성 필요', '설비투자 실행력 검증'],
    preferentialConditions: ['녹색전환 기업 우대', '보증료 감면', '탄소중립 지원'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '녹색전환 투자 기업 지원' },
  },
  {
    id: 'kibo-good-job',
    institutionId: 'kibo',
    track: 'policy_linked',
    name: '굿잡보증',
    shortName: '기보 굿잡',
    type: 'guarantee',
    description: '일자리 창출·확대 기업 전용 우대 보증',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['최근 1년 내 고용 증가 기업', '또는 고용 확대 계획 보유', '정규직 채용 우대'],
      excludedIndustries: ['부동산업', '금융업'],
    },
    terms: {
      amount: { max: 3000000000, unit: '억원', description: '최대 30억원' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['사업계획서', '재무제표', '고용보험 가입 증명원', '채용계획서'],
      applicationMethod: '기보 영업점',
      contactInfo: '1544-1120',
    },
    riskFactors: ['고용 증가 실적 또는 계획 필요', '정규직 중심 평가'],
    preferentialConditions: ['고용 증가 기업 우대', '보증료 감면', '한도 우대'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '일자리 창출 기업 전용' },
  },
  {
    id: 'kibo-new-growth',
    institutionId: 'kibo',
    track: 'policy_linked',
    name: '신성장분야보증',
    shortName: '기보 신성장',
    type: 'guarantee',
    description: 'AI, IoT, 빅데이터 등 4차산업혁명 신성장 분야 기업 지원',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['4차산업혁명 관련 업종', 'AI, IoT, 빅데이터, 블록체인 등', '신성장 분야 기술 보유'],
      requiredConditions: { hasTechnologyCertification: true },
      excludedIndustries: ['부동산업', '금융업'],
    },
    terms: {
      amount: { max: 5000000000, unit: '억원', description: '최대 50억원' },
      guaranteeRatio: { min: 85, max: 100, description: '보증비율 85~100%' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['사업계획서', '재무제표', '기술보유 증빙 (특허, 인증 등)'],
      applicationMethod: '기보 영업점',
      contactInfo: '1544-1120',
    },
    riskFactors: ['4차산업 분야 기술력 입증 필요', '시장성 평가'],
    preferentialConditions: ['신성장 분야 우대', '보증료 감면', '기술 컨설팅 연계'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '4차산업혁명 신성장 분야 기업 지원' },
  },
  {
    id: 'kibo-social-venture',
    institutionId: 'kibo',
    track: 'exclusive',
    name: '소셜벤처보증',
    shortName: '기보 소셜벤처',
    type: 'guarantee',
    description: '사회적가치 창출 기술혁신 기업 및 (예비)사회적기업 전용',
    fundingPurpose: { working: true, facility: true },
    eligibility: {
      additionalRequirements: ['사회적 가치 창출 기술혁신 기업', '(예비)사회적기업', '사회적 약자 보호, 환경 보전, 일자리 제공'],
      requiredConditions: { isSocialEconomyEnterprise: true },
      excludedIndustries: ['부동산업', '금융업'],
    },
    terms: {
      amount: { max: 1000000000, unit: '억원', description: '최대 10억원' },
      guaranteeRatio: { min: 90, max: 100, description: '보증비율 90~100%' },
    },
    practicalInfo: {
      processingTime: '약 2주',
      requiredDocuments: ['사업계획서', '사회적기업 인증서 (또는 예비)', '사회적가치 측정 보고서'],
      applicationMethod: '기보 영업점',
      contactInfo: '1544-1120',
    },
    riskFactors: ['사회적가치 창출 입증 필요', '인증 서류 필수'],
    preferentialConditions: ['사회적기업 전용', '보증료 감면', '높은 보증비율'],
    officialUrl: 'https://www.kibo.or.kr',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '사회적가치 창출 기업 전용' },
  },
  {
    id: 'kibo-one-click',
    institutionId: 'kibo',
    track: 'guarantee',
    name: '원클릭보증',
    shortName: '기보 원클릭',
    type: 'guarantee',
    description: '온라인 빅데이터 기반 간편 보증 (영업점 방문 불필요)',
    fundingPurpose: { working: true, facility: false },
    eligibility: {
      businessAge: { min: 1, description: '업력 1년 이상' },
      additionalRequirements: ['온라인 신청 가능 기업', '기존 기보 거래 실적 있으면 유리'],
      excludedIndustries: ['부동산업', '금융업'],
    },
    terms: {
      amount: { max: 200000000, unit: '억원', description: '최대 2억원' },
      guaranteeRatio: { min: 85, max: 95, description: '보증비율 85~95%' },
    },
    practicalInfo: {
      processingTime: '즉시~1일',
      requiredDocuments: ['사업자등록증', '대표자 신분증', '(추가 서류 최소화)'],
      applicationMethod: '기보 디지털지점 온라인',
      contactInfo: '1544-1120',
    },
    riskFactors: ['한도 제한적 (최대 2억)', '빅데이터 평가 기반'],
    preferentialConditions: ['영업점 방문 불필요', '빠른 심사 (즉시~1일)', '온라인 간편 신청'],
    officialUrl: 'https://www.kibo.or.kr/dbranch/index.do',
    meta: { lastUpdated: '2026-01', confidence: 0.85, notes: '온라인 빅데이터 기반 간편 보증' },
  },
];

// ============================================================================
// 통합 Knowledge Base
// ============================================================================

export const POLICY_FUND_KNOWLEDGE_BASE: PolicyFundKnowledge[] = [
  ...kosmesFunds,
  ...semasFunds,
  ...koditFunds,
  ...kiboFunds,
];

// ============================================================================
// 유틸리티 함수
// ============================================================================

export function getFundsByInstitution(institutionId: InstitutionId): PolicyFundKnowledge[] {
  return POLICY_FUND_KNOWLEDGE_BASE.filter(fund => fund.institutionId === institutionId);
}

export function getFundsByType(type: 'loan' | 'guarantee' | 'grant'): PolicyFundKnowledge[] {
  return POLICY_FUND_KNOWLEDGE_BASE.filter(fund => fund.type === type);
}

export function getFundById(id: string): PolicyFundKnowledge | undefined {
  return POLICY_FUND_KNOWLEDGE_BASE.find(fund => fund.id === id);
}

export function getAllFunds(): PolicyFundKnowledge[] {
  return POLICY_FUND_KNOWLEDGE_BASE;
}

export function getInstitutionInfo(id: InstitutionId): InstitutionInfo {
  return INSTITUTIONS[id];
}
