/**
 * lib/policy-fund/last/presets.ts
 *
 * /test 페이지 전용 테스트 프리셋 시나리오
 * 다양한 기업 유형별 테스트 데이터
 */

import type { PresetScenario } from './ui-types';

// ============================================================================
// 테스트 프리셋 시나리오
// ============================================================================

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'youth-venture',
    name: '청년 벤처',
    description: '청년창업 제조 벤처기업',
    emoji: '🚀',
    profile: {
      companyName: '(주)청년테크',
      industry: 'manufacturing_general',
      location: '경기',
      establishedYear: 2022,
      establishedMonth: 3,
      establishedDay: 15,
      annualRevenue: 25,
      employeeCount: 15,
      debtRatio: 50,
      isVenture: true,
      isInnobiz: false,
      isMainbiz: false,
      hasPatent: true,
      hasResearchInstitute: false,
      hasExportRecord: false,
      ceoAge: 32,
      isFemale: false,
      isDisabled: false,
      isDisabledStandard: false,
      isSocialEnterprise: false,
      isInactive: false,
      hasTaxDelinquency: false,
      hasTaxInstallmentApproval: false,
      isCurrentlyDelinquent: false,
      hasUnresolvedGuaranteeAccident: false,
      hasPastDefault: false,
      isPastDefaultResolved: false,
      isCreditRecoveryInProgress: false,
      existingLoanBalance: 0,
      isRestart: false,
      kosmesPreviousCount: 0,
      hasRecentKosmesLoan: false,
      currentGuaranteeOrg: 'none',
      recentYearSubsidyAmount: 0,
      isYouthStartupAcademyGrad: false,
      isGlobalStartupAcademyGrad: false,
      hasKiboYouthGuarantee: false,
      hasSmartFactoryPlan: false,
      hasEsgInvestmentPlan: false,
      isEmergencySituation: false,
      hasJobCreation: false,
      isGreenEnergyBusiness: false,
      hasIpoOrInvestmentPlan: false,
      hasVentureInvestment: false,
      acceptsEquityDilution: false,
      needsLargeFunding: false,
      requiredFundingAmount: 3,
      fundingPurposeWorking: true,
      fundingPurposeFacility: true,
    },
  },
  {
    id: 'youth-academy-grad',
    name: '청창사 졸업',
    description: '청년창업사관학교 졸업 기업 (업력 5년)',
    emoji: '🎓',
    profile: {
      companyName: '(주)청창사테크',
      industry: 'it_software',
      location: '서울',
      establishedYear: 2020,
      establishedMonth: 6,
      establishedDay: 1,
      annualRevenue: 15,
      employeeCount: 8,
      debtRatio: 40,
      isVenture: true,
      isInnobiz: false,
      isMainbiz: false,
      hasPatent: true,
      hasResearchInstitute: false,
      hasExportRecord: false,
      ceoAge: 34,
      isFemale: false,
      isDisabled: false,
      isDisabledStandard: false,
      isSocialEnterprise: false,
      isInactive: false,
      hasTaxDelinquency: false,
      hasTaxInstallmentApproval: false,
      isCurrentlyDelinquent: false,
      hasUnresolvedGuaranteeAccident: false,
      hasPastDefault: false,
      isPastDefaultResolved: false,
      isCreditRecoveryInProgress: false,
      existingLoanBalance: 0,
      isRestart: false,
      kosmesPreviousCount: 0,
      hasRecentKosmesLoan: false,
      currentGuaranteeOrg: 'none',
      recentYearSubsidyAmount: 0,
      isYouthStartupAcademyGrad: true,
      isGlobalStartupAcademyGrad: false,
      hasKiboYouthGuarantee: false,
      hasSmartFactoryPlan: false,
      hasEsgInvestmentPlan: false,
      isEmergencySituation: false,
      hasJobCreation: false,
      isGreenEnergyBusiness: false,
      hasIpoOrInvestmentPlan: false,
      hasVentureInvestment: false,
      acceptsEquityDilution: false,
      needsLargeFunding: false,
      requiredFundingAmount: 5,
      fundingPurposeWorking: true,
      fundingPurposeFacility: true,
    },
  },
  {
    id: 'micro-enterprise',
    name: '소공인',
    description: '10인 미만 제조 가공업체',
    emoji: '🔧',
    profile: {
      companyName: '(주)정밀가공',
      industry: 'manufacturing_root',
      location: '서울',
      establishedYear: 2017,
      establishedMonth: 1,
      establishedDay: 10,
      annualRevenue: 3,
      employeeCount: 5,
      debtRatio: 30,
      isVenture: false,
      isInnobiz: false,
      isMainbiz: false,
      hasPatent: false,
      hasResearchInstitute: false,
      hasExportRecord: false,
      ceoAge: 50,
      isFemale: false,
      isDisabled: false,
      isDisabledStandard: false,
      isSocialEnterprise: false,
      isInactive: false,
      hasTaxDelinquency: false,
      hasTaxInstallmentApproval: false,
      isCurrentlyDelinquent: false,
      hasUnresolvedGuaranteeAccident: false,
      hasPastDefault: false,
      isPastDefaultResolved: false,
      isCreditRecoveryInProgress: false,
      existingLoanBalance: 0,
      isRestart: false,
      kosmesPreviousCount: 0,
      hasRecentKosmesLoan: false,
      currentGuaranteeOrg: 'none',
      recentYearSubsidyAmount: 0,
      isYouthStartupAcademyGrad: false,
      isGlobalStartupAcademyGrad: false,
      hasKiboYouthGuarantee: false,
      hasSmartFactoryPlan: false,
      hasEsgInvestmentPlan: false,
      isEmergencySituation: false,
      hasJobCreation: false,
      isGreenEnergyBusiness: false,
      hasIpoOrInvestmentPlan: false,
      hasVentureInvestment: false,
      acceptsEquityDilution: false,
      needsLargeFunding: false,
      requiredFundingAmount: 1,
      fundingPurposeWorking: true,
      fundingPurposeFacility: true,
    },
  },
  {
    id: 'export-company',
    name: '수출기업',
    description: '수출 실적 보유 제조기업',
    emoji: '🌏',
    profile: {
      companyName: '(주)글로벌테크',
      industry: 'manufacturing_general',
      location: '인천',
      establishedYear: 2018,
      establishedMonth: 5,
      establishedDay: 20,
      annualRevenue: 100,
      employeeCount: 80,
      debtRatio: 80,
      isVenture: false,
      isInnobiz: true,
      isMainbiz: false,
      hasPatent: true,
      hasResearchInstitute: false,
      hasExportRecord: true,
      ceoAge: 48,
      isFemale: false,
      isDisabled: false,
      isDisabledStandard: false,
      isSocialEnterprise: false,
      isInactive: false,
      hasTaxDelinquency: false,
      hasTaxInstallmentApproval: false,
      isCurrentlyDelinquent: false,
      hasUnresolvedGuaranteeAccident: false,
      hasPastDefault: false,
      isPastDefaultResolved: false,
      isCreditRecoveryInProgress: false,
      existingLoanBalance: 5,
      isRestart: false,
      kosmesPreviousCount: 0,
      hasRecentKosmesLoan: false,
      currentGuaranteeOrg: 'none',
      recentYearSubsidyAmount: 0,
      isYouthStartupAcademyGrad: false,
      isGlobalStartupAcademyGrad: false,
      hasKiboYouthGuarantee: false,
      hasSmartFactoryPlan: false,
      hasEsgInvestmentPlan: false,
      isEmergencySituation: false,
      hasJobCreation: false,
      isGreenEnergyBusiness: false,
      hasIpoOrInvestmentPlan: false,
      hasVentureInvestment: false,
      acceptsEquityDilution: false,
      needsLargeFunding: false,
      requiredFundingAmount: 5,
      fundingPurposeWorking: true,
      fundingPurposeFacility: true,
    },
  },
  {
    id: 'rnd-company',
    name: 'R&D 기업',
    description: '연구개발 중심 기술기업',
    emoji: '🔬',
    profile: {
      companyName: '(주)테크연구소',
      industry: 'knowledge_service',
      location: '대전',
      establishedYear: 2020,
      establishedMonth: 9,
      establishedDay: 1,
      annualRevenue: 30,
      employeeCount: 25,
      debtRatio: 40,
      isVenture: true,
      isInnobiz: false,
      isMainbiz: false,
      hasPatent: true,
      hasResearchInstitute: true,
      hasExportRecord: false,
      ceoAge: 42,
      isFemale: false,
      isDisabled: false,
      isDisabledStandard: false,
      isSocialEnterprise: false,
      isInactive: false,
      hasTaxDelinquency: false,
      hasTaxInstallmentApproval: false,
      isCurrentlyDelinquent: false,
      hasUnresolvedGuaranteeAccident: false,
      hasPastDefault: false,
      isPastDefaultResolved: false,
      isCreditRecoveryInProgress: false,
      existingLoanBalance: 2,
      isRestart: false,
      kosmesPreviousCount: 0,
      hasRecentKosmesLoan: false,
      currentGuaranteeOrg: 'none',
      recentYearSubsidyAmount: 0,
      isYouthStartupAcademyGrad: false,
      isGlobalStartupAcademyGrad: false,
      hasKiboYouthGuarantee: false,
      hasSmartFactoryPlan: false,
      hasEsgInvestmentPlan: false,
      isEmergencySituation: false,
      hasJobCreation: false,
      isGreenEnergyBusiness: false,
      hasIpoOrInvestmentPlan: false,
      hasVentureInvestment: false,
      acceptsEquityDilution: false,
      needsLargeFunding: false,
      requiredFundingAmount: 10,
      fundingPurposeWorking: true,
      fundingPurposeFacility: true,
    },
  },
  {
    id: 'smart-factory',
    name: '스마트공장',
    description: '스마트공장 추진 제조기업',
    emoji: '🏭',
    profile: {
      companyName: '(주)스마트제조',
      industry: 'manufacturing_root',
      location: '경기',
      establishedYear: 2015,
      establishedMonth: 4,
      establishedDay: 15,
      annualRevenue: 80,
      employeeCount: 60,
      debtRatio: 70,
      isVenture: false,
      isInnobiz: false,
      isMainbiz: true,
      hasPatent: false,
      hasResearchInstitute: false,
      hasExportRecord: false,
      ceoAge: 55,
      isFemale: false,
      isDisabled: false,
      isDisabledStandard: false,
      isSocialEnterprise: false,
      isInactive: false,
      hasTaxDelinquency: false,
      hasTaxInstallmentApproval: false,
      isCurrentlyDelinquent: false,
      hasUnresolvedGuaranteeAccident: false,
      hasPastDefault: false,
      isPastDefaultResolved: false,
      isCreditRecoveryInProgress: false,
      existingLoanBalance: 10,
      isRestart: false,
      kosmesPreviousCount: 0,
      hasRecentKosmesLoan: false,
      currentGuaranteeOrg: 'none',
      recentYearSubsidyAmount: 0,
      isYouthStartupAcademyGrad: false,
      isGlobalStartupAcademyGrad: false,
      hasKiboYouthGuarantee: false,
      hasSmartFactoryPlan: false,
      hasEsgInvestmentPlan: false,
      isEmergencySituation: false,
      hasJobCreation: false,
      isGreenEnergyBusiness: false,
      hasIpoOrInvestmentPlan: false,
      hasVentureInvestment: false,
      acceptsEquityDilution: false,
      needsLargeFunding: false,
      requiredFundingAmount: 8,
      fundingPurposeWorking: true,
      fundingPurposeFacility: true,
    },
  },
  {
    id: 'restart-company',
    name: '재창업',
    description: '성실실패 후 재도전 기업',
    emoji: '🔄',
    profile: {
      companyName: '(주)재도전',
      industry: 'manufacturing_general',
      location: '서울',
      establishedYear: 2023,
      establishedMonth: 2,
      establishedDay: 1,
      annualRevenue: 5,
      employeeCount: 8,
      debtRatio: 60,
      isVenture: false,
      isInnobiz: false,
      isMainbiz: false,
      hasPatent: false,
      hasResearchInstitute: false,
      hasExportRecord: false,
      ceoAge: 35,
      isFemale: false,
      isDisabled: false,
      isDisabledStandard: false,
      isSocialEnterprise: false,
      isInactive: false,
      hasTaxDelinquency: false,
      hasTaxInstallmentApproval: false,
      isCurrentlyDelinquent: false,
      hasUnresolvedGuaranteeAccident: false,
      hasPastDefault: false,
      isPastDefaultResolved: false,
      isCreditRecoveryInProgress: false,
      existingLoanBalance: 0,
      isRestart: true,
      kosmesPreviousCount: 0,
      hasRecentKosmesLoan: false,
      currentGuaranteeOrg: 'none',
      recentYearSubsidyAmount: 0,
      isYouthStartupAcademyGrad: false,
      isGlobalStartupAcademyGrad: false,
      hasKiboYouthGuarantee: false,
      hasSmartFactoryPlan: false,
      hasEsgInvestmentPlan: false,
      isEmergencySituation: false,
      hasJobCreation: false,
      isGreenEnergyBusiness: false,
      hasIpoOrInvestmentPlan: false,
      hasVentureInvestment: false,
      acceptsEquityDilution: false,
      needsLargeFunding: false,
      requiredFundingAmount: 3,
      fundingPurposeWorking: true,
      fundingPurposeFacility: true,
    },
  },
  {
    id: 'crisis-company',
    name: '위기기업',
    description: '체납/연체 있는 기업 (제외 케이스)',
    emoji: '⚠️',
    profile: {
      companyName: '(주)경영위기',
      industry: 'manufacturing_general',
      location: '경기',
      establishedYear: 2020,
      establishedMonth: 7,
      establishedDay: 1,
      annualRevenue: 20,
      employeeCount: 20,
      debtRatio: 200,
      isVenture: false,
      isInnobiz: false,
      isMainbiz: false,
      hasPatent: false,
      hasResearchInstitute: false,
      hasExportRecord: false,
      ceoAge: 45,
      isFemale: false,
      isDisabled: false,
      isDisabledStandard: false,
      isSocialEnterprise: false,
      isInactive: false,
      hasTaxDelinquency: true,
      hasTaxInstallmentApproval: false,
      isCurrentlyDelinquent: true,
      hasUnresolvedGuaranteeAccident: false,
      hasPastDefault: false,
      isPastDefaultResolved: false,
      isCreditRecoveryInProgress: false,
      existingLoanBalance: 15,
      isRestart: false,
      kosmesPreviousCount: 0,
      hasRecentKosmesLoan: false,
      currentGuaranteeOrg: 'none',
      recentYearSubsidyAmount: 0,
      isYouthStartupAcademyGrad: false,
      isGlobalStartupAcademyGrad: false,
      hasKiboYouthGuarantee: false,
      hasSmartFactoryPlan: false,
      hasEsgInvestmentPlan: false,
      isEmergencySituation: false,
      hasJobCreation: false,
      isGreenEnergyBusiness: false,
      hasIpoOrInvestmentPlan: false,
      hasVentureInvestment: false,
      acceptsEquityDilution: false,
      needsLargeFunding: false,
      requiredFundingAmount: 2,
      fundingPurposeWorking: true,
      fundingPurposeFacility: true,
    },
  },
];
